spring:
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false
  datasource:
    driverClassName: "org.postgresql.Driver"
    hikari:
      maximum-pool-size: 4
      max-lifetime: 300000
  main:
    banner-mode: "off"
  data:
    jdbc:
      dialect: postgresql

server:
  port: 8080
  servlet:
    session:
      timeout: 2592000
    encoding:
      force: true
  error:
    whitelabel:
      enabled: false

swampy:
  schedule:
    timezone: "America/Los_Angeles"

    daily: "0 0 2 * * *"

    rss: "0 30 * * * *"

    phil:
      dadjoke: "0 17 7 * * *"
      humpday: "0 1 7 * * WED"
      dailyrandomnumber: "0 1 19 * * *"

    behrad:
      humpday: "0 2 7 * * WED"

    keanu:
      goodmorning: "0 0 7 * * *"

    events:
      # We're skipping the hours surrounding 2am (because of the daily tasks)
      boost: "0 0 0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"

      map: "0 37 1,5,9,13,17,21 * * *"
      quotetrivia: "0 37 2,6,10,14,18,22 * * *"
      trivia: "0 37 3,7,11,15,19,23 * * *"
      nsfwquotetrivia: "0 37 0,4,8,12,16,20 * * *"

      trickortreat: "0 3 9 * * *"
